#!/bin/sh

# prefix add [PLAT-xxx] and description add branch name

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
BRANCH_NAME=$(git symbolic-ref --short HEAD)

JIRA_TICKET=$(echo $BRANCH_NAME | grep -op "PLAT-\d*")

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop dev staging)
fi

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [ -n "$BRANCH_NAME" ] && ! [[ -z $JIRA_TICKET ]] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e "1s|^|[$JIRA_TICKET] |" $1

  echo "\n\nFrom ${BRANCH_NAME}" >> "$1"
fi
